com:
  example:
    lenovo:
      driver:
        downloader:
          download-configuration:
            # 配置源类型：URL（需要配置driver-list-new-url-path-base）、DriveListFile
            source-type: URL
            # 驱动列表下载的基础url 适配：source-type: URL
            driver-list-new-url-path-base: https://newsupport.lenovo.com.cn/api/drive/drive_listnew
            # 驱动存放目录 适配：source-type: URL
            target-base-folder: target/drives
            # 驱动列表文件路径 适配：source-type: DriveListFile
            # source-drive-list-file-path: target/drives/20220708224501/drives/drive_listnew
            drives-folder-name: drives
            # 是否使用日期作为下载目录的子目录 适配：save-date-pattern
            use-date-as-sub-folder: true
            # 日期样式 适配：use-date-as-sub-folder
            save-date-pattern: yyyyMMddHHmmss
            # url参数
            parameter-search-key: 12357
            parameter-sys-id: 42
            # 工作线程属
            work-threads-count: 10