com:
  example:
    lenovo:
      driver:
        downloader:
          download-configuration:
            # 驱动下载站点类型: Lenovo, ThinkPad
            driver-site-type: Lenovo
            # 驱动列表下载的基础url 适配：source-type: URL
            driver-list-new-url-path-base: https://newsupport.lenovo.com.cn/api/drive/drive_listnew
            # ThinkPad中驱动详情的基础url 适配：source-type: URL
            driver-detail-url-path-base-for-thinkpad: https://newsupport.lenovo.com.cn/api/drive/driver_detailnew
            # 驱动存放目录 适配：source-type: URL
            target-base-folder: target/drives
            # 驱动列表文件路径 适配：source-type: DriveListFile
            # source-drive-list-file-path: ../drivers/drive_listnew
            drives-folder-name: drives
            # 是否使用日期作为下载目录的子目录 适配：save-date-pattern
            use-date-as-forder-path-segment: true
            # 是否为每个驱动配置一个不同的下载时间。默认为false。
            use-same-date-for-each-url-parameter-config: false
            # 日期样式 适配：use-date-as-sub-folder
            save-date-pattern: yyyyMMddHHmmss
            url-parameter-configs:
              - # 配置源类型：URL（需要配置driver-list-new-url-path-base）、DriveListFile
                source-type: URL
                # url参数
                parameter-search-key: 10203
                parameter-sys-id: 26
              - # 配置源类型：URL（需要配置driver-list-new-url-path-base）、DriveListFile
                source-type: URL
                # url参数
                parameter-search-key: 10203
                parameter-sys-id: 42
            # 失败后的重试次数 默认负值（无限次）
            retry-times-when-fail: -1
            # 工作线程属
            work-threads-count: 10